In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import importlib
import pickle
import aux_functions as aux
importlib.reload(aux)

In [4]:
MONKEY = 'M08'
AREA = 'v4'

In [5]:
### Full cell list from a given monkey (every area, concatenated)

dicio_cell_list = {}
for area in ['ofc','te','teo','v4','vpa']:
    file_path = f'cell list {MONKEY}\\cell list {area}.txt' 
    dicio_cell_list[area] = aux.get_dataframe_cell_list(file_path)
    print(f'{area} data read and saved')
df_cell = pd.concat([item for item in dicio_cell_list.values()],axis=0)
df_cell

ofc data read and saved
te data read and saved
teo data read and saved
v4 data read and saved
vpa data read and saved

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,
0,1,m08cat072spk010b,m08det071spk010b,A+2+7,946,OFC,0.0,NaN,NaN,-0.10514,NaN,NaN,Focal Foveal,m08cat072,spk010b,NaN,NaN
1,2,m08cat072spk012b,m08det071spk012b,A+2+7,966,OFC,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m08cat072,spk012b,NaN,NaN
2,3,m08cat075spk021b,m08det074spk021b,A+2+7,980,OFC,NaN,0.0,NaN,NaN,,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18...",Peripheral,m08cat075,spk021b,NaN,NaN
3,4,m08cat075spk029b,m08det074spk029b,A+2+7,1060,OFC,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m08cat075,spk029b,NaN,NaN
4,5,m08cat081spk012b,m08det080spk012b,A+0+7,1310,OFC,0.0,0.0,house,NaN,NaN,NaN,Broad Foveal,m08cat081,spk012b,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1176,1206,m08cat261spk089a,m08det260spk089a,B+4-4,805,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat261,spk089a,NaN,NaN
1177,1207,m08cat261spk089z,m08det260spk089z,B+4-4,805,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat261,spk089z,NaN,NaN
1178,1208,m08cat261spk091a,m08det260spk091a,B+4-4,820,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat261,spk091a,NaN,NaN
1179,1209,m08cat261spk093a,m08det260spk093a,B+4-4,835,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat261,spk093a,NaN,NaN
1180,1210,m08cat261spk095a,m08det260spk095a,B+4-4,850,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat261,spk095a,NaN,NaN

In [ ]:
# OR just an area

# input(f'saving only {AREA} data. ok?')
# df_cell = aux.get_dataframe_cell_list(f'cell list {MONKEY}\\cell list {AREA}.txt')
# df_cell

In [11]:
df_v4 = df_cell[df_cell['brain_area']=='V4']
df_fov = df_v4[df_v4['RF_type'] == 'Focal Foveal']
df_nfov = df_v4[df_v4['RF_type'] != 'Focal Foveal']
df_fov


# df_fov = df_cell[df_cell['RF_type'] == 'Focal Foveal']
# df_nfov = df_cell[df_cell['RF_type'] != 'Focal Foveal']
# df_fov

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,
2,3,m08cat120spk033c,m08det119spk033c,+3+1,660,V4,0.0,NaN,house,-0.382790,NaN,NaN,Focal Foveal,m08cat120,spk033c,NaN,NaN
3,4,m08cat120spk033z,m08det119spk033z,+3+1,660,V4,0.0,NaN,face,0.243480,NaN,NaN,Focal Foveal,m08cat120,spk033z,NaN,NaN
54,55,m08cat129spk098a,m08det128spk098a,+3-4,1110,V4,0.0,NaN,face,0.075061,NaN,NaN,Focal Foveal,m08cat129,spk098a,NaN,NaN
55,56,m08cat129spk098z,m08det128spk098z,+3-4,1110,V4,0.0,NaN,NaN,0.071743,NaN,NaN,Focal Foveal,m08cat129,spk098z,NaN,NaN
60,61,m08cat129spk100a,m08det128spk100a,+3-4,1130,V4,0.0,NaN,face,0.151440,NaN,NaN,Focal Foveal,m08cat129,spk100a,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2262,2263,m08cat261spk127a,m08det260spk127a,+3-3,876,V4,0.0,NaN,face,0.103660,NaN,NaN,Focal Foveal,m08cat261,spk127a,NaN,NaN
2263,2264,m08cat261spk127b,m08det260spk127b,+3-3,876,V4,0.0,NaN,face,0.210830,NaN,NaN,Focal Foveal,m08cat261,spk127b,NaN,NaN
2264,2265,m08cat261spk127z,m08det260spk127z,+3-3,876,V4,0.0,NaN,face,0.111990,NaN,NaN,Focal Foveal,m08cat261,spk127z,NaN,NaN
2265,2266,m08cat261spk128a,m08det260spk128a,+3-3,1036,V4,0.0,NaN,face,0.206670,NaN,NaN,Focal Foveal,m08cat261,spk128a,NaN,NaN
2266,2267,m08cat261spk128z,m08det260spk128z,+3-3,1036,V4,0.0,NaN,face,0.286230,NaN,NaN,Focal Foveal,m08cat261,spk128z,NaN,NaN

In [12]:
df_qtd_neurons = pd.DataFrame({'Non Foveal': df_nfov['session'].value_counts(), 'Foveal': df_fov['session'].value_counts(),'Total':df_cell['session'].value_counts()}).fillna(0).sort_values('Foveal',ascending=False)
df_qtd_neurons['Pct Foveal'] = 100 * df_qtd_neurons['Foveal'] / df_qtd_neurons['Total']
df_qtd_neurons[df_qtd_neurons['Foveal']>=4]

           Non Foveal  Foveal  Total  Pct Foveal
m08cat255         0.0    87.0    231   37.662338
m08cat252         9.0    66.0    215   30.697674
m08cat261         4.0    60.0    168   35.714286
m08cat258         5.0    57.0    145   39.310345
m08cat129        27.0    48.0    143   33.566434
m08cat249        17.0    47.0    130   36.153846
m08cat243        31.0    27.0    127   21.259843
m08cat240        44.0    24.0    148   16.216216
m08cat204        49.0    16.0    177    9.039548
m08cat156        53.0    15.0    156    9.615385
m08cat246        38.0    12.0     72   16.666667
m08cat195        68.0    11.0    230    4.782609
m08cat201        60.0     6.0    232    2.586207
m08cat234        46.0     5.0     97    5.154639
m08cat198        69.0     4.0    209    1.913876

In [8]:
SESSION = 'm08cat255'

In [ ]:
# input(f'saving only {SESSION} data and ONLY FOVEAL. ok?')
# df_session = df_fov[df_fov['session']==SESSION]
# df_session

In [17]:
df_session = df_cell[df_cell['session']==SESSION]
df_session

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,
763,847,m08cat255spk033a,m08det254spk033a,-1+5,1186,TE,0.0,NaN,face,0.38549,NaN,NaN,Focal Foveal,m08cat255,spk033a,NaN,NaN
764,848,m08cat255spk033z,m08det254spk033z,-1+5,1186,TE,0.0,NaN,face,0.51208,NaN,NaN,Focal Foveal,m08cat255,spk033z,NaN,NaN
765,849,m08cat255spk034a,m08det254spk034a,-1+5,1346,TE,0.0,NaN,face,0.60449,NaN,NaN,Focal Foveal,m08cat255,spk034a,NaN,NaN
766,850,m08cat255spk034b,m08det254spk034b,-1+5,1346,TE,0.0,NaN,face,1.00000,NaN,NaN,Focal Foveal,m08cat255,spk034b,NaN,NaN
767,851,m08cat255spk034c,m08det254spk034c,-1+5,1346,TE,0.0,0.0,face,0.56654,"0,8,19","1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,20",Broad Foveal,m08cat255,spk034c,"0,8,19",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111,1140,m08cat255spk091b,m08det254spk091b,B+4-4,720,VPA,0.0,0.0,NaN,0.13946,NaN,NaN,Broad Foveal,m08cat255,spk091b,NaN,NaN
1112,1141,m08cat255spk091z,m08det254spk091z,B+4-4,720,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat255,spk091z,NaN,NaN
1113,1142,m08cat255spk093b,m08det254spk093b,B+4-4,735,VPA,0.0,0.0,NaN,-0.36007,NaN,NaN,Broad Foveal,m08cat255,spk093b,NaN,NaN
1114,1143,m08cat255spk095a,m08det254spk095a,B+4-4,750,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat255,spk095a,NaN,NaN
1115,1144,m08cat255spk095b,m08det254spk095b,B+4-4,750,VPA,0.0,0.0,NaN,-0.18893,NaN,NaN,Broad Foveal,m08cat255,spk095b,NaN,NaN

In [28]:
df_session.index = pd.Index(range(len(df_session.index)))
df_session

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,
0,847,m08cat255spk033a,m08det254spk033a,-1+5,1186,TE,0.0,NaN,face,0.38549,NaN,NaN,Focal Foveal,m08cat255,spk033a,NaN,NaN
1,848,m08cat255spk033z,m08det254spk033z,-1+5,1186,TE,0.0,NaN,face,0.51208,NaN,NaN,Focal Foveal,m08cat255,spk033z,NaN,NaN
2,849,m08cat255spk034a,m08det254spk034a,-1+5,1346,TE,0.0,NaN,face,0.60449,NaN,NaN,Focal Foveal,m08cat255,spk034a,NaN,NaN
3,850,m08cat255spk034b,m08det254spk034b,-1+5,1346,TE,0.0,NaN,face,1.00000,NaN,NaN,Focal Foveal,m08cat255,spk034b,NaN,NaN
4,851,m08cat255spk034c,m08det254spk034c,-1+5,1346,TE,0.0,0.0,face,0.56654,"0,8,19","1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,20",Broad Foveal,m08cat255,spk034c,"0,8,19",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,1140,m08cat255spk091b,m08det254spk091b,B+4-4,720,VPA,0.0,0.0,NaN,0.13946,NaN,NaN,Broad Foveal,m08cat255,spk091b,NaN,NaN
227,1141,m08cat255spk091z,m08det254spk091z,B+4-4,720,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat255,spk091z,NaN,NaN
228,1142,m08cat255spk093b,m08det254spk093b,B+4-4,735,VPA,0.0,0.0,NaN,-0.36007,NaN,NaN,Broad Foveal,m08cat255,spk093b,NaN,NaN
229,1143,m08cat255spk095a,m08det254spk095a,B+4-4,750,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat255,spk095a,NaN,NaN
230,1144,m08cat255spk095b,m08det254spk095b,B+4-4,750,VPA,0.0,0.0,NaN,-0.18893,NaN,NaN,Broad Foveal,m08cat255,spk095b,NaN,NaN

In [30]:
with open(f"session_data\\{SESSION}.pkl", "wb") as file:
    pickle.dump(df_session, file)

In [14]:
df_session['brain_area'].value_counts()

TE     106
V4      87
VPA     38
Name: brain_area, dtype: int64

In [16]:
df_session = df_session[df_session['brain_area']=='V4']

In [ ]:
path_destiny = f'dados\\{MONKEY}_neurons\\neurons sorted'
list_neuron_ids = df_session['search']
list_prefered_cat = df_session['prefer']
list_brain_area = df_session['brain_area']
list_RF_type = df_session['RF_type']

# OBS: spike times here stop in the END OF THE FIRST FIX!!! We can alter later for posterior analysis.
df_trials = aux.get_df_trials(list_neuron_ids, path_destiny, list(list_prefered_cat), list(list_brain_area), list(list_RF_type), firings_cue_and_array=True)
df_trials

In [59]:
# sacc_start	start_first_fix	end_first_fix
# plt.hist(df_trials['start_first_fix'] - df_trials['sacc_start'], bins=np.arange(-0.05,0.1,0.01),cumulative=False,density=True)
# plt.hist(df_trials['end_first_fix']-df_trials['start_first_fix'] , bins=np.arange(-0.2,0.5,0.01),cumulative=False,density=True)