In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import importlib
import pickle
import aux_functions as aux
importlib.reload(aux)

In [38]:
# MONKEY = 'M08'
MONKEY = 'M06'
# AREA = 'v4'

In [39]:
### Full cell list from a given monkey (every area, concatenated)

dicio_cell_list = {}
for area in ['ofc','te','teo','v4','vpa']:
    file_path = f'cell list {MONKEY}\\cell list {area}.txt' 
    dicio_cell_list[area] = aux.get_dataframe_cell_list(file_path)
    print(f'{area} data read and saved')
df_cell = pd.concat([item for item in dicio_cell_list.values()],axis=0)
df_cell

ofc data read and saved
te data read and saved
teo data read and saved
v4 data read and saved
vpa data read and saved

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,"0,1,2,3,5,6,7,8,9,10,11,13,14,15,18,19,20","0,1,2,3,8,9,10,11,12,13,14,16,17,18,19,20"
0,1,m06cat006spk006a,m06det005spk006a,-3+5,495,OFC,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m06cat006,spk006a,NaN,NaN,NaN
1,2,m06cat006spk006b,m06det005spk006b,-3+5,495,OFC,0.0,NaN,NaN,0.270360,NaN,NaN,Focal Foveal,m06cat006,spk006b,NaN,NaN,NaN
2,3,m06cat006spk008a,m06det005spk008a,-3+5,510,OFC,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m06cat006,spk008a,NaN,NaN,NaN
3,4,m06cat006spk008b,m06det005spk008b,-3+5,510,OFC,0.0,NaN,NaN,-0.242090,NaN,NaN,Focal Foveal,m06cat006,spk008b,NaN,NaN,NaN
4,5,m06cat006spk010a,m06det005spk010a,-3+5,525,OFC,0.0,NaN,NaN,-0.100340,NaN,NaN,Focal Foveal,m06cat006,spk010a,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1814,2013,m06cat288spk094a,m06det287spk094a,+4-2,567,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m06cat288,spk094a,NaN,NaN,NaN
1815,2014,m06cat288spk094z,m06det287spk094z,+4-2,567,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m06cat288,spk094z,NaN,NaN,NaN
1816,2015,m06cat288spk095a,m06det287spk095a,+4-2,417,VPA,0.0,0.0,NaN,-0.040015,"0,2,3,4,5,6,10,11,12,13,14,15","1,7,8,9,16,17,18,19,20",Broad Foveal,m06cat288,spk095a,"2,3,4,5,11,12,13,14",NaN,NaN
1817,2016,m06cat288spk095b,m06det287spk095b,+4-2,417,VPA,NaN,0.0,NaN,-0.034345,"2,3,4,5,6,10,12,13,14","0,1,7,8,9,11,16,17,18,19,20",Peripheral,m06cat288,spk095b,NaN,NaN,NaN
1818,2017,m06cat288spk095z,m06det287spk095z,+4-2,417,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m06cat288,spk095z,NaN,NaN,NaN

In [ ]:
# OR just an area

# input(f'saving only {AREA} data. ok?')
# df_cell = aux.get_dataframe_cell_list(f'cell list {MONKEY}\\cell list {AREA}.txt')
# df_cell

In [40]:
df_v4 = df_cell[df_cell['brain_area']=='V4']
df_fov = df_v4[df_v4['RF_type'] == 'Focal Foveal']
df_nfov = df_v4[df_v4['RF_type'] != 'Focal Foveal']
df_fov


# df_fov = df_cell[df_cell['RF_type'] == 'Focal Foveal']
# df_nfov = df_cell[df_cell['RF_type'] != 'Focal Foveal']
# df_fov

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,"0,1,2,3,5,6,7,8,9,10,11,13,14,15,18,19,20","0,1,2,3,8,9,10,11,12,13,14,16,17,18,19,20"
0,1,m06cat108spk097a,m06det107spk097a,+3-2,320,V4,0.0,NaN,house,-1.000000,NaN,NaN,Focal Foveal,m06cat108,spk097a,NaN,NaN,NaN
3,4,m06cat108spk098z,m06det107spk098z,+3-2,640,V4,0.0,NaN,NaN,0.139960,NaN,NaN,Focal Foveal,m06cat108,spk098z,NaN,NaN,NaN
4,5,m06cat108spk099a,m06det107spk099a,+3-2,340,V4,0.0,NaN,house,-0.506890,NaN,NaN,Focal Foveal,m06cat108,spk099a,NaN,NaN,NaN
5,6,m06cat108spk099z,m06det107spk099z,+3-2,340,V4,0.0,NaN,house,-0.562900,NaN,NaN,Focal Foveal,m06cat108,spk099z,NaN,NaN,NaN
8,9,m06cat108spk100z,m06det107spk100z,+3-2,660,V4,0.0,NaN,house,-0.177840,NaN,NaN,Focal Foveal,m06cat108,spk100z,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3073,3074,m06cat288spk126z,m06det287spk126z,+2-5,688,V4,0.0,NaN,NaN,0.073817,NaN,NaN,Focal Foveal,m06cat288,spk126z,NaN,NaN,NaN
3076,3077,m06cat288spk128a,m06det287spk128a,+2-5,698,V4,0.0,NaN,face,0.041171,NaN,NaN,Focal Foveal,m06cat288,spk128a,NaN,NaN,NaN
3077,3078,m06cat288spk128b,m06det287spk128b,+2-5,698,V4,0.0,NaN,NaN,0.103600,NaN,NaN,Focal Foveal,m06cat288,spk128b,NaN,NaN,NaN
3078,3079,m06cat288spk128c,m06det287spk128c,+2-5,698,V4,0.0,NaN,NaN,0.046372,NaN,NaN,Focal Foveal,m06cat288,spk128c,NaN,NaN,NaN
3079,3080,m06cat288spk128z,m06det287spk128z,+2-5,698,V4,0.0,NaN,NaN,0.070168,NaN,NaN,Focal Foveal,m06cat288,spk128z,NaN,NaN,NaN

In [41]:
df_qtd_neurons = pd.DataFrame({'Non Foveal': df_nfov['session'].value_counts(), 'Foveal': df_fov['session'].value_counts(),'Total':df_v4['session'].value_counts()}).fillna(0).sort_values('Foveal',ascending=False)
df_qtd_neurons['Pct Foveal'] = 100 * df_qtd_neurons['Foveal'] / df_qtd_neurons['Total']
df_qtd_neurons[df_qtd_neurons['Foveal']>=4]

           Non Foveal  Foveal  Total  Pct Foveal
m06cat279          25    65.0     90   72.222222
m06cat282          13    56.0     69   81.159420
m06cat213          19    53.0     72   73.611111
m06cat210          46    51.0     97   52.577320
m06cat207          36    50.0     86   58.139535
m06cat186          12    50.0     62   80.645161
m06cat237           8    48.0     56   85.714286
m06cat174          28    46.0     74   62.162162
m06cat192          42    45.0     87   51.724138
m06cat111           9    43.0     52   82.692308
m06cat165          11    43.0     54   79.629630
m06cat108           9    42.0     51   82.352941
m06cat159          12    39.0     51   76.470588
m06cat168          15    38.0     53   71.698113
m06cat183          11    36.0     47   76.595745
m06cat288          44    34.0     78   43.589744
m06cat231          34    33.0     67   49.253731
m06cat162          14    33.0     47   70.212766
m06cat177          46    31.0     77   40.259740
m06cat129          19    30.0     49   61.224490
m06cat180          38    29.0     67   43.283582
m06cat261          43    29.0     72   40.277778
m06cat120          11    28.0     39   71.794872
m06cat189          19    28.0     47   59.574468
m06cat156          13    28.0     41   68.292683
m06cat171          14    28.0     42   66.666667
m06cat255          30    27.0     57   47.368421
m06cat285          38    27.0     65   41.538462
m06cat264          67    24.0     91   26.373626
m06cat114          24    23.0     47   48.936170
m06cat249          31    22.0     53   41.509434
m06cat216          16    20.0     36   55.555556
m06cat267          25    20.0     45   44.444444
m06cat234          36    20.0     56   35.714286
m06cat195          11    20.0     31   64.516129
m06cat252          26    17.0     43   39.534884
m06cat276          15    15.0     30   50.000000
m06cat126          43    15.0     58   25.862069
m06cat258          22    14.0     36   38.888889
m06cat219          11    11.0     22   50.000000
m06cat222          14    10.0     24   41.666667
m06cat246          66    10.0     76   13.157895
m06cat117           4     9.0     13   69.230769
m06cat240          46     9.0     55   16.363636
m06cat147          48     8.0     56   14.285714
m06cat198           4     8.0     12   66.666667
m06cat270          40     8.0     48   16.666667
m06cat135          40     7.0     47   14.893617
m06cat132          43     7.0     50   14.000000
m06cat243          70     4.0     74    5.405405
m06cat273          36     4.0     40   10.000000
m06cat228          10     4.0     14   28.571429

In [ ]:
# SESSION = 'm08cat255'
# SESSION = 'm08cat252'
# SESSION = 'm08cat261'
# SESSION = 'm08cat129'
# SESSION = 'm08cat156'

# SESSION = "m06cat279"
# SESSION = "m06cat210"
# SESSION = "m06cat192"

In [ ]:
# input(f'saving only {SESSION} data and ONLY FOVEAL. ok?')
# df_session = df_fov[df_fov['session']==SESSION]
# df_session

In [56]:
df_session = df_cell[df_cell['session']==SESSION]
print(df_session['brain_area'].value_counts())
df_session.index = pd.Index(range(len(df_session.index)))
df_session

V4     87
VPA    52
Name: brain_area, dtype: int64

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,"0,1,2,3,5,6,7,8,9,10,11,13,14,15,18,19,20","0,1,2,3,8,9,10,11,12,13,14,16,17,18,19,20"
0,1398,m06cat192spk097a,m06det191spk097a,+3-7,241,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m06cat192,spk097a,NaN,NaN,NaN
1,1399,m06cat192spk097b,m06det191spk097b,+3-7,241,V4,NaN,0.0,NaN,0.302960,6,"0,1,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,1...",Peripheral,m06cat192,spk097b,NaN,NaN,NaN
2,1400,m06cat192spk097z,m06det191spk097z,+3-7,241,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m06cat192,spk097z,NaN,NaN,NaN
3,1401,m06cat192spk098a,m06det191spk098a,+3-7,401,V4,0.0,NaN,house,-0.039441,NaN,NaN,Focal Foveal,m06cat192,spk098a,NaN,NaN,NaN
4,1402,m06cat192spk098b,m06det191spk098b,+3-7,401,V4,0.0,NaN,NaN,0.108700,NaN,NaN,Focal Foveal,m06cat192,spk098b,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,190,m06cat192spk093a,m06det191spk093a,+3+0,391,VPA,0.0,0.0,NaN,0.072759,"0,2,3,4,5,10,11,12,13,14","1,6,7,8,9,15,16,17,18,19,20",Broad Foveal,m06cat192,spk093a,"2,3,4,5,10,11,12,13,14",NaN,NaN
135,191,m06cat192spk093b,m06det191spk093b,+3+0,391,VPA,NaN,0.0,house,-0.451600,"12,13,3,4,11","0,1,2,5,6,7,8,9,10,14,15,16,17,18,19,20",Peripheral,m06cat192,spk093b,NaN,NaN,NaN
136,193,m06cat192spk095a,m06det191spk095a,+3+0,401,VPA,NaN,0.0,house,-0.341630,"4,13,10,11,12,3","0,6,1,2,5,7,8,9,14,15,16,17,18,19,20",Peripheral,m06cat192,spk095a,NaN,NaN,NaN
137,194,m06cat192spk095z,m06det191spk095z,+3+0,401,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m06cat192,spk095z,NaN,NaN,NaN
138,195,m06cat192spk096a,m06det191spk096a,+3+0,561,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m06cat192,spk096a,NaN,NaN,NaN

In [57]:
with open(f"session_data\\{SESSION}.pkl", "wb") as file:
    pickle.dump(df_session, file)

In [ ]:
# df_session = df_session[df_session['brain_area']=='V4']

In [ ]:
# path_destiny = f'dados\\{MONKEY}_neurons\\neurons sorted'
# list_neuron_ids = df_session['search']
# list_prefered_cat = df_session['prefer']
# list_brain_area = df_session['brain_area']
# list_RF_type = df_session['RF_type']

# # OBS: spike times here stop in the END OF THE FIRST FIX!!! We can alter later for posterior analysis.
# df_trials = aux.get_df_trials(list_neuron_ids, path_destiny, list(list_prefered_cat), list(list_brain_area), list(list_RF_type), firings_cue_and_array=True)
# df_trials

In [59]:
# sacc_start	start_first_fix	end_first_fix
# plt.hist(df_trials['start_first_fix'] - df_trials['sacc_start'], bins=np.arange(-0.05,0.1,0.01),cumulative=False,density=True)
# plt.hist(df_trials['end_first_fix']-df_trials['start_first_fix'] , bins=np.arange(-0.2,0.5,0.01),cumulative=False,density=True)