In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import importlib
import pickle
import aux_functions as aux
importlib.reload(aux)

In [2]:
MONKEY = 'M08'
SESSION = 'm08cat156'
STR_DETAILS = f'Session {SESSION}'

In [3]:
with open(f"session_data/{SESSION}.pkl", "rb") as file:
    df_session= pickle.load(file)
df_session

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,
0,193,m08cat156spk002a,m08det155spk002a,B-5+0,726,OFC,0.0,NaN,NaN,0.27540,NaN,NaN,Focal Foveal,m08cat156,spk002a,NaN,NaN
1,194,m08cat156spk006a,m08det155spk006a,B-5+0,746,OFC,0.0,NaN,face,0.66811,NaN,NaN,Focal Foveal,m08cat156,spk006a,NaN,NaN
2,195,m08cat156spk008a,m08det155spk008a,B-5+0,756,OFC,0.0,NaN,NaN,1.00000,NaN,NaN,Focal Foveal,m08cat156,spk008a,NaN,NaN
3,196,m08cat156spk012a,m08det155spk012a,B-5+0,776,OFC,0.0,NaN,NaN,0.70578,NaN,NaN,Focal Foveal,m08cat156,spk012a,NaN,NaN
4,197,m08cat156spk014a,m08det155spk014a,B-5+0,786,OFC,0.0,NaN,face,1.00000,NaN,NaN,Focal Foveal,m08cat156,spk014a,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,609,m08cat156spk125b,m08det155spk125b,+1-5,970,V4,0.0,NaN,NaN,0.11156,NaN,NaN,Focal Foveal,m08cat156,spk125b,NaN,NaN
152,610,m08cat156spk125z,m08det155spk125z,+1-5,970,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m08cat156,spk125z,NaN,NaN
153,611,m08cat156spk127a,m08det155spk127a,+1-5,990,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m08cat156,spk127a,NaN,NaN
154,612,m08cat156spk127b,m08det155spk127b,+1-5,990,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m08cat156,spk127b,NaN,NaN
155,613,m08cat156spk127z,m08det155spk127z,+1-5,990,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m08cat156,spk127z,NaN,NaN

In [ ]:
df_session['RF_type'].unique()

array(['Focal Foveal', 'Broad Foveal', 'Peripheral'], dtype=object)

In [6]:
df_session[df_session['RF_type']=='Peripheral']

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,
88,546,m08cat156spk097a,m08det155spk097a,+1-5,690,V4,NaN,0.0,NaN,0.096865,"5,6,15","0,9,1,2,3,4,7,8,10,11,12,13,14,16,17,18,19,20",Peripheral,m08cat156,spk097a,NaN,NaN
89,547,m08cat156spk097z,m08det155spk097z,+1-5,690,V4,NaN,0.0,NaN,0.161360,"5,6","0,1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20",Peripheral,m08cat156,spk097z,NaN,NaN
91,549,m08cat156spk098b,m08det155spk098b,+1-5,1010,V4,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat156,spk098b,NaN,NaN
93,551,m08cat156spk099a,m08det155spk099a,+1-5,710,V4,NaN,0.0,NaN,0.071550,"5,6","0,10,1,2,3,4,7,8,9,11,12,13,14,15,16,17,18,19,20",Peripheral,m08cat156,spk099a,NaN,NaN
94,552,m08cat156spk099z,m08det155spk099z,+1-5,710,V4,NaN,0.0,NaN,0.235220,"6,5","0,1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20",Peripheral,m08cat156,spk099z,NaN,NaN
98,556,m08cat156spk101a,m08det155spk101a,+1-5,730,V4,NaN,0.0,NaN,0.123180,"5,6","0,1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20",Peripheral,m08cat156,spk101a,NaN,NaN
99,557,m08cat156spk101z,m08det155spk101z,+1-5,730,V4,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat156,spk101z,NaN,NaN
105,563,m08cat156spk103a,m08det155spk103a,+1-5,750,V4,NaN,0.0,NaN,0.415990,"5,6","0,18,1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,19,20",Peripheral,m08cat156,spk103a,NaN,NaN
106,564,m08cat156spk103b,m08det155spk103b,+1-5,750,V4,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat156,spk103b,NaN,NaN
107,565,m08cat156spk103z,m08det155spk103z,+1-5,750,V4,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat156,spk103z,NaN,NaN
111,569,m08cat156spk105a,m08det155spk105a,+1-5,770,V4,NaN,0.0,NaN,0.014790,"5,6","0,1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20",Peripheral,m08cat156,spk105a,NaN,NaN
112,570,m08cat156spk105z,m08det155spk105z,+1-5,770,V4,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat156,spk105z,NaN,NaN
116,574,m08cat156spk107a,m08det155spk107a,+1-5,790,V4,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat156,spk107a,NaN,NaN
117,575,m08cat156spk107z,m08det155spk107z,+1-5,790,V4,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat156,spk107z,NaN,NaN
122,580,m08cat156spk109z,m08det155spk109z,+1-5,810,V4,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat156,spk109z,NaN,NaN
129,587,m08cat156spk111c,m08det155spk111c,+1-5,830,V4,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat156,spk111c,NaN,NaN
130,588,m08cat156spk111z,m08det155spk111z,+1-5,830,V4,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat156,spk111z,NaN,NaN

In [7]:
df_session[df_session['RF_type']=='Broad Foveal']

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,
18,1807,m08cat156spk034a,m08det155spk034a,+1+3,1686,TEO,0.0,0.0,NaN,0.004952,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18...",,Broad Foveal,m08cat156,spk034a,"0,2,4,5,6,12,15",NaN
19,1808,m08cat156spk034b,m08det155spk034b,+1+3,1686,TEO,0.0,0.0,NaN,-0.002620,"0,4,5,6,13,14","1,2,3,7,8,9,10,11,12,15,16,17,18,19,20",Broad Foveal,m08cat156,spk034b,"0,4,5,6,13",NaN
20,1809,m08cat156spk034c,m08det155spk034c,+1+3,1686,TEO,0.0,0.0,NaN,0.030485,"0,2,3,4,5,6,13,14","1,7,8,9,10,11,12,15,16,17,18,19,20",Broad Foveal,m08cat156,spk034c,"0,4",NaN
21,1810,m08cat156spk034d,m08det155spk034d,+1+3,1686,TEO,0.0,0.0,NaN,-0.005340,NaN,NaN,Broad Foveal,m08cat156,spk034d,NaN,NaN
22,1811,m08cat156spk034z,m08det155spk034z,+1+3,1686,TEO,0.0,0.0,NaN,0.014099,NaN,NaN,Broad Foveal,m08cat156,spk034z,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,608,m08cat156spk125a,m08det155spk125a,+1-5,970,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m08cat156,spk125a,NaN,NaN
152,610,m08cat156spk125z,m08det155spk125z,+1-5,970,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m08cat156,spk125z,NaN,NaN
153,611,m08cat156spk127a,m08det155spk127a,+1-5,990,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m08cat156,spk127a,NaN,NaN
154,612,m08cat156spk127b,m08det155spk127b,+1-5,990,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m08cat156,spk127b,NaN,NaN
155,613,m08cat156spk127z,m08det155spk127z,+1-5,990,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m08cat156,spk127z,NaN,NaN