## Question 1: Can the foveal neuron activity pattern decode the target cathegory BEFORE the saccade?

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import importlib
import pickle
import aux_functions as aux
importlib.reload(aux)

In [2]:
MONKEY = 'M08'
AREA = 'V4'
SESSION = 'm08cat255'

In [3]:
with open(f"session_data\\{SESSION}.pkl", "rb") as file:
    df_session= pickle.load(file)
df_session

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,
0,847,m08cat255spk033a,m08det254spk033a,-1+5,1186,TE,0.0,NaN,face,0.38549,NaN,NaN,Focal Foveal,m08cat255,spk033a,NaN,NaN
1,848,m08cat255spk033z,m08det254spk033z,-1+5,1186,TE,0.0,NaN,face,0.51208,NaN,NaN,Focal Foveal,m08cat255,spk033z,NaN,NaN
2,849,m08cat255spk034a,m08det254spk034a,-1+5,1346,TE,0.0,NaN,face,0.60449,NaN,NaN,Focal Foveal,m08cat255,spk034a,NaN,NaN
3,850,m08cat255spk034b,m08det254spk034b,-1+5,1346,TE,0.0,NaN,face,1.00000,NaN,NaN,Focal Foveal,m08cat255,spk034b,NaN,NaN
4,851,m08cat255spk034c,m08det254spk034c,-1+5,1346,TE,0.0,0.0,face,0.56654,"0,8,19","1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,20",Broad Foveal,m08cat255,spk034c,"0,8,19",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,1140,m08cat255spk091b,m08det254spk091b,B+4-4,720,VPA,0.0,0.0,NaN,0.13946,NaN,NaN,Broad Foveal,m08cat255,spk091b,NaN,NaN
227,1141,m08cat255spk091z,m08det254spk091z,B+4-4,720,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat255,spk091z,NaN,NaN
228,1142,m08cat255spk093b,m08det254spk093b,B+4-4,735,VPA,0.0,0.0,NaN,-0.36007,NaN,NaN,Broad Foveal,m08cat255,spk093b,NaN,NaN
229,1143,m08cat255spk095a,m08det254spk095a,B+4-4,750,VPA,NaN,0.0,NaN,NaN,NaN,NaN,Peripheral,m08cat255,spk095a,NaN,NaN
230,1144,m08cat255spk095b,m08det254spk095b,B+4-4,750,VPA,0.0,0.0,NaN,-0.18893,NaN,NaN,Broad Foveal,m08cat255,spk095b,NaN,NaN

In [5]:
df_session = df_session[df_session['brain_area']==AREA]
df_session

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,
106,2055,m08cat255spk097z,m08det254spk097z,+3-3,716,V4,0.0,NaN,NaN,-0.285580,NaN,NaN,Focal Foveal,m08cat255,spk097z,NaN,NaN
107,2056,m08cat255spk098a,m08det254spk098a,+3-3,876,V4,0.0,NaN,face,0.108970,NaN,NaN,Focal Foveal,m08cat255,spk098a,NaN,NaN
108,2057,m08cat255spk098b,m08det254spk098b,+3-3,876,V4,0.0,NaN,face,0.176950,NaN,NaN,Focal Foveal,m08cat255,spk098b,NaN,NaN
109,2058,m08cat255spk098z,m08det254spk098z,+3-3,876,V4,0.0,NaN,NaN,0.026967,NaN,NaN,Focal Foveal,m08cat255,spk098z,NaN,NaN
110,2059,m08cat255spk099a,m08det254spk099a,+3-3,726,V4,0.0,NaN,NaN,-0.085379,NaN,NaN,Focal Foveal,m08cat255,spk099a,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188,2137,m08cat255spk128a,m08det254spk128a,+3-3,1026,V4,0.0,NaN,face,0.206230,NaN,NaN,Focal Foveal,m08cat255,spk128a,NaN,NaN
189,2138,m08cat255spk128b,m08det254spk128b,+3-3,1026,V4,0.0,NaN,face,0.233680,NaN,NaN,Focal Foveal,m08cat255,spk128b,NaN,NaN
190,2139,m08cat255spk128c,m08det254spk128c,+3-3,1026,V4,0.0,NaN,face,0.690970,NaN,NaN,Focal Foveal,m08cat255,spk128c,NaN,NaN
191,2140,m08cat255spk128d,m08det254spk128d,+3-3,1026,V4,0.0,NaN,face,1.000000,NaN,NaN,Focal Foveal,m08cat255,spk128d,NaN,NaN
192,2141,m08cat255spk128z,m08det254spk128z,+3-3,1026,V4,0.0,NaN,NaN,0.137630,NaN,NaN,Focal Foveal,m08cat255,spk128z,NaN,NaN

In [6]:
path_destiny = f'dados\\{MONKEY}_neurons\\neurons sorted'
list_neuron_ids = df_session['search']
list_prefered_cat = df_session['prefer']
list_brain_area = df_session['brain_area']
list_RF_type = df_session['RF_type']

# OBS: spike times here stop in the END OF THE FIRST FIX!!! We can alter later for posterior analysis.
df_trials = aux.get_df_trials(list_neuron_ids, path_destiny, list(list_prefered_cat), list(list_brain_area), list(list_RF_type), firings_cue_and_array=False)
df_trials

,neuron,prefered,brain_area,RF_type,trial_num,clue_id,clue_cath,imgsacc_id,imgsacc_cath,pre_sacc_time,FP_on,fix_FP,clue_on,clue_off,FP_back,array_on,sacc_start,start_first_fix,end_first_fix,firings
0,m08cat255spk097z,NaN,V4,Focal Foveal,3,1020.0,flower,2030.0,house,0.137433,5.065133,5.152433,5.580300,6.266300,6.266667,6.793967,6.931400,6.947333,7.057100,"[-1.6521999999999997, -1.5935333333333332, -1...."
1,m08cat255spk097z,NaN,V4,Focal Foveal,4,3022.0,face,3022.0,face,0.155533,8.988067,9.227933,9.634067,10.168367,10.168700,10.675167,10.830700,10.832767,11.640533,"[-1.6550333333333338, -1.5921666666666674, -1...."
2,m08cat255spk097z,NaN,V4,Focal Foveal,5,2020.0,house,3005.0,face,0.165867,12.695667,12.698533,13.105633,13.931633,13.932000,14.438333,14.604200,14.607900,14.794833,"[-1.7332, -1.6857333333333333, -1.611033333333..."
3,m08cat255spk097z,NaN,V4,Focal Foveal,7,3019.0,face,1017.0,flower,0.163433,19.097333,19.343733,19.750333,20.874867,20.875200,21.381600,21.545033,21.547100,21.694867,"[-2.4454666666666647, -2.2130666666666663, -2...."
4,m08cat255spk097z,NaN,V4,Focal Foveal,8,2013.0,house,3019.0,face,0.139000,23.554733,23.689867,24.096733,24.610267,24.610633,25.117100,25.256100,25.259900,25.462067,"[-1.5441000000000003, -1.539366666666666, -1.4..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150679,m08cat255spk128z,NaN,V4,Focal Foveal,2657,3007.0,face,2024.0,house,0.139367,12806.472433,12806.608333,12807.014333,12807.576533,12807.576900,12808.083233,12808.222600,12808.226200,12808.469667,"[-1.6588333333329501, -1.5046333333320945, -1...."
150680,m08cat255spk128z,NaN,V4,Focal Foveal,2658,2051.0,house,4020.0,hand,0.144167,12810.638433,12810.797333,12811.201200,12811.749333,12811.749700,12812.256100,12812.400267,12812.402700,12812.405467,"[-1.7314333333342802, -1.6982333333344286, -1...."
150681,m08cat255spk128z,NaN,V4,Focal Foveal,2662,3017.0,face,2019.0,house,0.149333,12824.955233,12825.235133,12825.643000,12826.913367,12826.913733,12827.420033,12827.569367,12827.571467,12827.975533,"[-2.538266666666459, -2.440233333332799, -2.42..."
150682,m08cat255spk128z,NaN,V4,Focal Foveal,2663,2050.0,house,2019.0,house,0.122767,12830.079367,12832.670533,12833.072167,12833.800967,12833.801333,12834.307667,12834.430433,12834.437167,12834.572567,"[-4.30256666666719, -4.272266666666837, -4.268..."
150683,m08cat255spk128z,NaN,V4,Focal Foveal,2669,3003.0,face,2027.0,house,0.156400,12854.442967,12857.533767,12857.935833,12858.442333,12858.442700,12858.949100,12859.105500,12859.107533,12859.298400,"[-4.594966666665641, -4.592366666665839, -4.57..."

## Plotting session details

In [11]:
# complete later with plots of create_tabelao

## Creating the DataFrame to train the model

In [7]:
def get_df_bins_presacc(df_trials, bins, bin_size):
    data_trials_run_model = []
    for trial in df_trials['trial_num'].unique():
        df_this_trial = df_trials[df_trials['trial_num']==trial]
        cat_target = df_this_trial.iloc[0]['imgsacc_cath']
        data_model_row = {'Y':cat_target}
        for index, row in df_this_trial.iterrows():
            neuron_id = row['neuron'][9:]
            firings = np.array(row['firings'])
            counts, _ = np.histogram(firings, bins=bins)
            FR = counts / bin_size
            for i, _ in enumerate(bins[:-1]):
                data_model_row[f'{neuron_id}_Bin{i+1}'] = FR[i]
        data_trials_run_model.append(data_model_row)
    return  pd.DataFrame(data_trials_run_model)

In [8]:
bins = np.array([-0.2,-0.15,-0.1,-0.05,0.0])
bin_size = 0.05

df_run_model = get_df_bins_presacc(df_trials, bins, bin_size)
df_run_model2 = df_run_model[df_run_model['Y'].isin(['house','face'])]
df_run_model

,Y,spk097z_Bin1,spk097z_Bin2,spk097z_Bin3,spk097z_Bin4,spk098a_Bin1,spk098a_Bin2,spk098a_Bin3,spk098a_Bin4,spk098b_Bin1,...,spk128c_Bin3,spk128c_Bin4,spk128d_Bin1,spk128d_Bin2,spk128d_Bin3,spk128d_Bin4,spk128z_Bin1,spk128z_Bin2,spk128z_Bin3,spk128z_Bin4
0,house,0.0,20.0,0.0,0.0,100.0,120.0,100.0,60.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,0.0
1,face,0.0,0.0,20.0,0.0,0.0,40.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,face,0.0,20.0,0.0,0.0,20.0,60.0,0.0,40.0,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,20.0,20.0,20.0,0.0
3,flower,0.0,0.0,0.0,20.0,80.0,60.0,40.0,60.0,0.0,...,0.0,0.0,20.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0
4,face,0.0,20.0,20.0,0.0,0.0,20.0,20.0,20.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1727,house,0.0,0.0,0.0,0.0,20.0,0.0,0.0,60.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,60.0,20.0
1728,hand,20.0,0.0,0.0,0.0,60.0,40.0,20.0,0.0,20.0,...,0.0,0.0,0.0,0.0,0.0,0.0,20.0,20.0,0.0,0.0
1729,house,20.0,0.0,0.0,0.0,20.0,0.0,20.0,20.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,0.0
1730,house,0.0,0.0,20.0,0.0,40.0,120.0,60.0,20.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,20.0,20.0,60.0,20.0
1731,house,0.0,0.0,20.0,0.0,20.0,40.0,40.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,20.0,60.0

In [38]:
# print(aux.preprocess_spikes(df_trials.iloc[0]['firings']))
# print(aux.preprocess_spikes(df_trials.iloc[0]['firings'],sigma=0))

# print(aux.preprocess_spikes(df_trials.iloc[1]['firings']))
# print(aux.preprocess_spikes(df_trials.iloc[1]['firings'],sigma=0))

In [37]:
def get_df_bins_presacc_smoothing(df_trials, bins, bin_size, sigma=15):
    data_trials_run_model = []
    for trial in df_trials['trial_num'].unique():
        df_this_trial = df_trials[df_trials['trial_num']==trial]
        cat_target = df_this_trial.iloc[0]['imgsacc_cath']
        data_model_row = {'Y':cat_target}
        for index, row in df_this_trial.iterrows():
            neuron_id = row['neuron'][9:]
            firings = np.array(row['firings'])
            FR = aux.preprocess_spikes(firings, sigma=sigma, bin_start=bins[0]*1000, bin_size=bin_size*1000, end_time=bins[-1]*1000)
            for i, _ in enumerate(bins[:-1]):
                data_model_row[f'{neuron_id}_Bin{i+1}'] = FR[i]
        data_trials_run_model.append(data_model_row)
    return  pd.DataFrame(data_trials_run_model)

bins = np.array([-0.2,-0.15,-0.1,-0.05,0.0])
bin_size = 0.05

get_df_bins_presacc_smoothing(df_trials, bins, bin_size, sigma=15)

,Y,spk097z_Bin1,spk097z_Bin2,spk097z_Bin3,spk097z_Bin4,spk098a_Bin1,spk098a_Bin2,spk098a_Bin3,spk098a_Bin4,spk098b_Bin1,...,spk128c_Bin3,spk128c_Bin4,spk128d_Bin1,spk128d_Bin2,spk128d_Bin3,spk128d_Bin4,spk128z_Bin1,spk128z_Bin2,spk128z_Bin3,spk128z_Bin4
0,house,3.344021,5.113276,14.881338,0.005317,139.769283,84.899165,99.805683,76.858757,0.000000,...,19.582632,0.409185,0.00000,0.000000,0.0,0.0,23.327502,0.005230,18.495443,1.475056
1,face,2.955106,0.000023,15.260898,4.646097,0.000000,20.142257,19.848691,0.008875,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000
2,face,0.014776,15.765312,4.234605,0.000081,43.287525,71.817417,3.097132,35.040747,19.976226,...,0.000000,0.000000,0.00000,0.000000,0.0,0.0,32.554993,23.059951,3.388506,16.564315
3,flower,0.199755,0.000000,0.000000,7.823046,80.913836,42.584201,70.325744,34.433756,0.000000,...,0.000000,0.000000,19.83786,0.199755,0.0,0.0,7.888453,18.006917,1.993670,0.000000
4,face,17.918154,19.847103,6.257995,13.630663,0.000000,19.962385,9.781604,14.086380,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.0,0.0,19.504633,0.496769,0.000000,19.561745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1727,house,0.000000,0.000000,0.000000,0.000000,18.890488,1.117992,0.000000,46.466258,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.0,0.0,1.994257,19.910417,56.061608,18.376139
1728,hand,12.118238,7.881175,0.000587,0.000000,57.225919,29.080735,37.668830,1.288483,19.503231,...,0.000000,0.000000,0.00000,0.000000,0.0,0.0,1.733526,21.019210,17.932930,0.011348
1729,house,15.765312,4.234605,0.000083,0.000000,15.795279,4.234605,6.093606,29.960017,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.0,0.0,8.003790,0.000318,19.865130,19.725583
1730,house,0.000000,0.000000,18.264730,1.701245,10.318031,121.956727,65.518618,34.926369,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.0,0.0,21.469009,2.117290,49.410442,46.760289
1731,house,0.000000,0.000000,3.097386,16.564315,18.264730,9.714777,71.769547,0.246026,0.000000,...,0.000000,0.000000,0.00000,0.000000,0.0,0.0,0.007331,8.878411,28.164605,57.826754

## Machine Learning

In [ ]:
# train-test-validation split
# z-scoring (POR NEURONIO!!!! NAO POR NEURONIO-BIN (e zscore treino é diferente de zscore teste))

# para cada modelo:
# cross validation 
# hyperparam tuning with bayesian search
# fazer seleção de modelos somente usando os conjuntos com mais de X neurônios? e dps testar em todos
# BIN SHUFFLING


# dps de rodar tudo, se nao der nada, ai questione o bin size e etc....
# testar: cortar 10-20ms? por possiveis erros do eye tracker?